// admin-dashboard/src/lib/Sidebar.svelte
<script>
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import icon from '$lib/assets/icon-512.png';

	function handleLogout() {
		document.cookie = 'otaship_token=; path=/; max-age=0';
		goto('/login');
	}
</script>

<div class="flex min-h-screen w-52 flex-col border-r border-gray-800">
	<div>
		<div class="flex items-center justify-center gap-2 p-8 text-2xl font-bold">
			<img src={icon} alt="OTAShip" width="32" height="32" class="rounded-lg" /> OTAShip
		</div>
		<hr class="mb-10 h-px border-0 border-gray-800 bg-gray-800" />
		<div class="px-4">
			<nav>
				<ul>
					{#each [{ href: '/', label: 'Overview' }, { href: '/projects', label: 'Projects' }, { href: '/settings', label: 'Settings' }] as link}
						<li class="mb-2">
							<a
								href={link.href}
								class="block rounded-lg px-4 py-2 transition-colors {page.url.pathname === link.href
									? 'bg-white font-medium text-black'
									: 'text-gray-400 hover:bg-gray-800 hover:text-white'}"
							>
								{link.label}
							</a>
						</li>
					{/each}
				</ul>
			</nav>
		</div>
	</div>

	<div class="mt-auto w-full px-4 pb-8">
		<hr class="mb-5 h-px border-0 border-gray-800 bg-gray-800" />
		<button
			onclick={handleLogout}
			class="w-full cursor-pointer rounded-lg bg-gray-800 px-4 py-2 text-white transition-colors hover:bg-gray-700"
			>Logout</button
		>
	</div>
</div>

// admin-dashboard/components/Sidebar.jsx
import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { LayoutDashboard, List, Box, Settings, LogOut } from 'lucide-react';

const Sidebar = ({ onLogout }) => {
  const router = useRouter();
  const currentPath = router.pathname;

  const items = [
    { id: 'overview', label: 'Overview', path: '/', icon: LayoutDashboard },
    { id: 'releases', label: 'Releases', path: '/releases', icon: List },
    { id: 'projects', label: 'Projects', path: '/projects', icon: Box },
    { id: 'settings', label: 'Settings', path: '/settings', icon: Settings },
  ];

  return (
    <aside className="w-64 bg-gray-900 border-r border-gray-800 flex flex-col h-screen fixed left-0 top-0 z-40 transition-transform">
      <div className="p-6 border-b border-gray-800 flex items-center">
        <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
          🚀 OTAShip
        </h1>
      </div>

      <nav className="flex-1 p-4 space-y-2 overflow-y-auto">
        {items.map((item) => {
          const Icon = item.icon;
          const isActive = currentPath === item.path;
          return (
            <Link
              key={item.id}
              href={item.path}
              className={`w-full flex items-center px-4 py-3 rounded-xl transition-all duration-200 group ${
                isActive
                  ? 'bg-blue-600/10 text-blue-400 border border-blue-500/20 shadow-[0_0_15px_rgba(59,130,246,0.1)]'
                  : 'text-gray-400 hover:text-white hover:bg-gray-800'
              }`}>
              <Icon
                className={`w-5 h-5 mr-3 transition-colors ${
                  isActive ? 'text-blue-400' : 'text-gray-500 group-hover:text-white'
                }`}
              />
              <span className="font-medium text-sm">{item.label}</span>
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t border-gray-800 bg-gray-900/50 backdrop-blur-sm">
        <button
          onClick={onLogout}
          className="w-full flex items-center px-4 py-3 text-red-400 hover:text-red-300 hover:bg-red-900/10 rounded-xl transition-colors border border-transparent hover:border-red-900/30">
          <LogOut className="w-5 h-5 mr-3" />
          <span className="font-medium text-sm">Logout</span>
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;
